name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node with latest LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test
      - uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Package updated: @${{ steps.publish.outputs.tag }} ${{ steps.publish.outputs.old-version }} -> ${{ steps.publish.outputs.version }}"
